[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Serial monitor baud rate
monitor_speed = 115200

; Libraries
lib_deps =
    kosme/arduinoFFT @ ^2.0.2
    bblanchon/ArduinoJson @ ^7.0.0
